<a href="https://colab.research.google.com/github/RichaTiwari14/Pytorch_trial/blob/main/torch_beginner.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import torch
import torch as nn
print(torch.__version__)
if torch.cuda.is_available():
  print("GPA available")
  print(torch.cuda.get_device_name())
else:
  print("GPU not available")



2.6.0+cu124
GPA available
Tesla T4


In [37]:
#empty() doesn't assign any value only allocates memory to the dimension and returns values already existing in that memory
print("Empty():",torch.empty(2,3))

#type()
a=torch.rand(2,3)
type(a) #returns type of the variable

#ones() assigns value 1 to the memory
torch.ones(2,2)

#zeros() assigns value 0 to the memory
torch.zeros(2,2)

#rand() assigns random values to the memory
torch.rand(2,2)

#manual_seed()   used to generate same random values....just use this rand() with the same manual_seed()
torch.manual_seed(100)
print(torch.rand(2,3))

#tensor() to direct assign the given values
torch.tensor([[2,3,4],[1.2,3.2,0.2]])

#arange() works same as range, give the initial and final(x-1) and step (i,f,s)value and it will return the values falling in between
torch.arange(0,10,2)

#linspace()
torch.linspace(0,10,10)

#eye() sets the dimension
torch.eye(10)

#full() first set dimension in bracket then value to assign in that memory
torch.full((3,3),5)

#shape()
(torch.tensor([[1,2,3],[1.2,3.2,6.2]])).shape

#OR

x=torch.tensor([[1,2,3],[1.2,3.2,6.2]])
x.shape

#empty_like() will generate empty() method value in the same dimension as x
torch.empty_like(x)

#zeros_like()
torch.zeros_like(x)

#ones_like()
torch.ones_like(x)

#rand_like()  won't work as the rest of methods generate int value whereas rand genrates floats between 0-1

#dtype() to know the data type
x.dtype

a=torch.tensor([1.2,2.3,3.4],dtype=torch.int32) #converting the given tensor into int
torch.tensor([2,3,4],dtype=torch.float64) # converting the given tensor into float

x.to(torch.int32) #converting the already existing tensor into another   eg.float to int
torch.rand_like(a,dtype=torch.float32) #

#ceil()
torch.ceil(a) #it gives nearest greater integer

#floor()
torch.floor(a) #it gives nearest smaller integer

print(a+2) #adddition
print(a-2) #subtraction
print(a*2)  #multiplication
print(a/2) #division ( returns float value)
print(a//2) #floor division (returns integer value)
print(a**2) #power
print(torch.abs(a))  #returns absolute value
print(torch.neg(a)) #returns negative value
print(torch.round(a)) #returns round figure
print(torch.clamp(a, min=2,max=5))  #returns value with min and max limit set
z=torch.randint(size=(2,3),low=3,high=10) #returns random integer values having limit set low, high
print(z)
print(torch.sum(z,dim=0)) #make sum of values of columns compressing it to the given dimension
print(torch.sum(z,dim=1))




Empty(): tensor([[1.1030e-21, 4.4364e-41, 2.3090e-33],
        [0.0000e+00, 2.1716e-33, 0.0000e+00]])
tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])
tensor([3, 4, 5], dtype=torch.int32)
tensor([-1,  0,  1], dtype=torch.int32)
tensor([2, 4, 6], dtype=torch.int32)
tensor([0.5000, 1.0000, 1.5000])
tensor([0, 1, 1], dtype=torch.int32)
tensor([1, 4, 9], dtype=torch.int32)
tensor([1, 2, 3], dtype=torch.int32)
tensor([-1, -2, -3], dtype=torch.int32)
tensor([1, 2, 3], dtype=torch.int32)
tensor([2, 2, 3], dtype=torch.int32)
tensor([[6, 7, 8],
        [8, 7, 5]])
tensor([14, 14, 13])
tensor([21, 20])
