<a href="https://colab.research.google.com/github/RichaTiwari14/Pytorch_trial/blob/main/torch_beginner2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import torch as nn
print(torch.__version__)
if torch.cuda.is_available():
  print("GPA available")
  print(torch.cuda.get_device_name())
else:
  print("GPU not available")



2.6.0+cu124
GPA available
Tesla T4


In [ ]:
#empty() doesn't assign any value only allocates memory to the dimension and returns values already existing in that memory
print("Empty():",torch.empty(2,3))

#type()
a=torch.rand(2,3)
type(a) #returns type of the variable

#ones() assigns value 1 to the memory
torch.ones(2,2)

#zeros() assigns value 0 to the memory
torch.zeros(2,2)

#rand() assigns random values to the memory
torch.rand(2,2)

#manual_seed()   used to generate same random values....just use this rand() with the same manual_seed()
torch.manual_seed(100)
print(torch.rand(2,3))

#tensor() to direct assign the given values
torch.tensor([[2,3,4],[1.2,3.2,0.2]])

#arange() works same as range, give the initial and final(x-1) and step (i,f,s)value and it will return the values falling in between
torch.arange(0,10,2)

#linspace()
torch.linspace(0,10,10)

#eye() sets the dimension
torch.eye(10)

#full() first set dimension in bracket then value to assign in that memory
torch.full((3,3),5)

#shape()
(torch.tensor([[1,2,3],[1.2,3.2,6.2]])).shape

#OR

x=torch.tensor([[1,2,3],[1.2,3.2,6.2]])
x.shape

#empty_like() will generate empty() method value in the same dimension as x
torch.empty_like(x)

#zeros_like()
torch.zeros_like(x)

#ones_like()
torch.ones_like(x)

#rand_like()  won't work as the rest of methods generate int value whereas rand genrates floats between 0-1

#dtype() to know the data type
x.dtype

a=torch.tensor([1.2,2.3,3.4],dtype=torch.int32) #converting the given tensor into int
torch.tensor([2,3,4],dtype=torch.float64) # converting the given tensor into float

x.to(torch.int32) #converting the already existing tensor into another   eg.float to int
torch.rand_like(a,dtype=torch.float32) #

#ceil()
torch.ceil(a) #it gives nearest greater integer

#floor()
torch.floor(a) #it gives nearest smaller integer

print(a+2) #adddition
print(a-2) #subtraction
print(a*2)  #multiplication
print(a/2) #division ( returns float value)
print(a//2) #floor division (returns integer value)
print(a**2) #power
print(torch.abs(a))  #returns absolute value
print(torch.neg(a)) #returns negative value
print(torch.round(a)) #returns round figure
print(torch.clamp(a, min=2,max=5))  #returns value with min and max limit set
z=torch.randint(size=(2,3),low=3,high=10) #returns random integer values having limit set low, high
print(z)
print(torch.sum(z,dim=0)) #make sum of values of columns compressing it to the given dimension
print(torch.sum(z,dim=1))

#mean() to use this method the tensor should be float, therefore convert it to float
e=z.to(torch.float32)
print(e)
print(torch.mean(e)) #mean of whole
print(torch.mean(e,dim=1)) #on the basis of row
print(torch.mean(e,dim=0)) #on the basis of col

#median()
print(torch.median(e)) #median of whole
print(torch.median(e,dim=0)) #on the basis of col
print(torch.median(e,dim=1)) #on the basis of row

#max() & min()
print(torch.max(e))
print(torch.min(e))

#prod() to find out product
print(torch.prod(e))

#std() to find out standard deviation
print(torch.std(e))

#var() to find out variance
print(torch.var(e))

#argmax() to find out the position of the max value
print(torch.argmax(e))

#argmin() to find out position of the min value
print(torch.argmin(e))



Empty(): tensor([[1.8123e+35, 4.5139e-41, 1.2572e-33],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])
tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])
tensor([3, 4, 5], dtype=torch.int32)
tensor([-1,  0,  1], dtype=torch.int32)
tensor([2, 4, 6], dtype=torch.int32)
tensor([0.5000, 1.0000, 1.5000])
tensor([0, 1, 1], dtype=torch.int32)
tensor([1, 4, 9], dtype=torch.int32)
tensor([1, 2, 3], dtype=torch.int32)
tensor([-1, -2, -3], dtype=torch.int32)
tensor([1, 2, 3], dtype=torch.int32)
tensor([2, 2, 3], dtype=torch.int32)
tensor([[6, 7, 8],
        [8, 7, 5]])
tensor([14, 14, 13])
tensor([21, 20])
tensor([[6., 7., 8.],
        [8., 7., 5.]])
tensor(6.8333)
tensor([7.0000, 6.6667])
tensor([7.0000, 7.0000, 6.5000])
tensor(7.)
torch.return_types.median(
values=tensor([6., 7., 5.]),
indices=tensor([0, 0, 1]))
torch.return_types.median(
values=tensor([7., 7.]),
indices=tensor([1, 1]))
tensor(8.)
tensor(5.)
tensor(94080.)
tensor(1.1690)
tensor(1.3667)
tensor(2)
tensor(5)


In [ ]:
#matrix multiplication
a=torch.tensor([[2.2,3.4,5.1],[4.2,5.2,3.2]])
b=torch.tensor([[3.3,4.2],[0.1,0.3],[2.2,3.3]])
torch.matmul(a,b)

tensor([[18.8200, 27.0900],
        [21.4200, 29.7600]])

In [ ]:
#dot products
vector1=torch.tensor([2,3])
vector2=torch.tensor([4,5])
print(torch.dot(vector1,vector2))

tensor(23)


In [ ]:
e #printing e without using print
torch.transpose(e,0,1)

tensor([[6., 8.],
        [7., 7.],
        [8., 5.]])


In [ ]:
a=torch.tensor([[1,2],[3,2]])
b=a.to(torch.float32)
torch.det(b)

tensor(-4.)

In [ ]:
#inverse()
torch.inverse(b)

tensor([[-0.5000,  0.5000],
        [ 0.7500, -0.2500]])

In [ ]:
a=torch.tensor([[2,2],[4,5]])
b=torch.tensor([[6,2],[8,1]])
#to compare each values
#comparision operator
print(a>b)
print(a<b)
print(a==b)
print(a!=b)
print(a<=b)
print(a>=b)



tensor([[False, False],
        [False,  True]])
tensor([[ True, False],
        [ True, False]])
tensor([[False,  True],
        [False, False]])
tensor([[ True, False],
        [ True,  True]])
tensor([[ True,  True],
        [ True, False]])
tensor([[False,  True],
        [False,  True]])


In [ ]:
#log() to find logrithm
a=torch.randint(size=(2,3),low=3,high=10)
b=a.to(torch.float32)
torch.log(a)

tensor([[1.0986, 1.3863, 2.0794],
        [2.1972, 2.1972, 1.3863]])

In [ ]:
#exponent exp()
torch.exp(a)


tensor([[  20.0855, 2980.9580,   54.5981],
        [  54.5981,  148.4132, 2980.9580]])

In [ ]:
#sqrt()
print(torch.sqrt(a))

#sigmoid()
print(torch.sigmoid(a))

#softmax()  not applicable for long
print(torch.softmax(b,dim=0))

tensor([[1.7321, 2.0000, 2.8284],
        [3.0000, 3.0000, 2.0000]])
tensor([[0.9526, 0.9820, 0.9997],
        [0.9999, 0.9999, 0.9820]])
tensor([[0.0025, 0.0067, 0.9820],
        [0.9975, 0.9933, 0.0180]])


In [ ]:
#relu() rectified linear unit
torch.relu(b)

tensor([[3., 4., 8.],
        [9., 9., 4.]])

In [ ]:
#inspace operation
#in general what happens, when we perform any operation the result is saved in another memory thus taking more space which is not actually a good practice
#therefore we can perform inspace operations

a=torch.tensor([2,3],dtype=torch.float32)
b=torch.tensor([3,4],dtype=torch.float32)
#add_()
a.add_(b)
print(a)

#sub_()
a.sub_(b)
print(a)

#mul_()
a.mul_(b)
print(a)

#div_()
a.div_(b)
print(a)

#performing inplace operation basically requires underscore at the last. eg. add_, sub_ ...

print(a.relu_()) # using this way to perform operation is permanently changing a tensor


tensor([5., 7.])
tensor([2., 3.])
tensor([ 6., 12.])
tensor([2., 3.])
tensor([2., 3.])


In [ ]:
a=torch.rand(2,3)
b=a # in basic manner it is assignment operator so what should happen is that the value of a should be assigned to b , but for a change it doesn't work this way here.
# instead it is like, that now you can access a from b also. so whatever changes will be there in b



IndexError: invalid index of a 0-dim tensor. Use `tensor.item()` in Python or `tensor.item<T>()` in C++ to convert a 0-dim tensor to a number